### ISSUE TITLE
Set Up Kanban Board

### ISSUE THREAD

**Issue by JohnFTitor** [JohnFTitor/catalog-of-stuff#16]
# Set up and assigned tasks regarding the development of the current project.

We're a team of 3 passionate developers. Our distribution goes like this:

- Team member # 1 @zhadier 
- Team member # 2 @JohnFTitor 
- Team member # 3 @Sahar-AbdelSamad 

You can find a [link to the kanban board here](https://github.com/JohnFTitor/catalog-of-stuff/projects/1)

<img src="https://media4.giphy.com/media/8UGGp7rQvfhe63HrFq/giphy.gif"/>

**Comment by julie-ify** [comment]
## APPROVED ✔️ ✔️

Hi @JohnFTitor, @Sahar-AbdelSamad @zhadier, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
